### ISSUE TITLE
App crash on updating profile on updating gpa page

### ISSUE THREAD

**Issue by parth-07** [XploreX/cgpa-book-android#23]
**Describe the bug**
Select semester info in **update gpa** is not cleared on updating profile (changing college, course, branch, semester etc). Thus if the updated combination of (college, course, branch) do not have semester already present in **update gpa** page, then requesting semester grading schema resource will return no data. Here on pressing next button on update gpa page app crashes.  

**To Reproduce**

1) Go to **update profile** and select following values:
    - College: Vardhman Mahavir Medical College and Safdarjung Hospital
    - Course: Doctor of Medicine
    - Branch: General Medicine

2) Now go to **Update GPA**, and select _final_ semester and then go back

3) Again, go to **update profile**, and this time select following values:
    - College: USICT
    - Course: Bachelor of Technology
    - Branch: Computer Science and Engineering

4) Go to **Update GPA**, and select go next without changing semester. App crashes now.

**Smartphone (please complete the following information):**
 - Device: Samsung M31
 - OS: Android
 - Version: 11

**Comment by manorit2001** [comment]
Thanks for reporting this, I'll be fixing this shortly
